### ISSUE TITLE
Add API key for LLM API

### ISSUE THREAD

**Issue by mbaddar1** [mbaddar1/llm-flow#27]

**Comment by mohammedmmansour** [comment]
API Key has been created and tested. every customer will need his API key. Also usage plan has been created for the testing purpose, as the API Key didn't work without the usage plan (not shown in AWS documentation).

You can use this in the header ('x-api-key': 'ndtODFPdtA3xhgfkAqVnh12oa7aIy52T9hRSA3zc')
