### ISSUE TITLE
Upload file via API Gateway

### ISSUE THREAD

**Issue by mbaddar1** [mbaddar1/llm-flow#30]
https://repost.aws/knowledge-center/api-gateway-upload-image-s3

**Comment by mohammedmmansour** [comment]
curl -i --location --request PUT 'https://mcw0rn675i.execute-api.eu-north-1.amazonaws.com/DEV/uploadeddatallm/testimage.jpeg' --header 'Content-Type: text/plain' --data-binary '@/Path/to/file/image.jpeg'
