### ISSUE TITLE
Relate the uploaded files with the API Key

### ISSUE THREAD

**Issue by mohammedmmansour** [mbaddar1/llm-flow#36]
Every file uploaded by the user should be stored under folder, this folder should be named after the API Key. 

Prerequisite: We need to validate if the API Key is always valid name for folder inside the S3 bucket.

**Comment by mbaddar1** [comment]
done
sample output in folder
s3://llm-index/CaGt3EXWN0eGI9qN9ePnq2xOuLLJSEDwIywewhV713smpaaTN5xqwUydsTYiFloxj1n6NTwyEMlYrdiWtwZau5dllyWSXpZC3iprAs9bNL1mafAaRIz1WrSUuSO6jHuF/
