### ISSUE TITLE
Link github pages to domain

### ISSUE THREAD

**Issue by betaflowai** [mbaddar1/llm-flow#75]
https://jinnabalu.medium.com/godaddy-domain-with-github-pages-62aed906d4ef

https://docs.github.com/en/pages/configuring-a-custom-domain-for-your-github-pages-site/troubleshooting-custom-domains-and-github-pages
https://docs.github.com/en/pages/configuring-a-custom-domain-for-your-github-pages-site

**Comment by betaflowai** [comment]
![image](https://github.com/betaflowai/answerme/assets/125094312/f2c1eff0-dd95-4527-8d94-e97cc56d75fc)

**Comment by mbaddar1** [comment]
finished, remaining the https part @mohammedmmansour
