### ISSUE TITLE
Finalize the landing page

### ISSUE THREAD

**Issue by mbaddar1** [mbaddar1/llm-flow#91]
http://betaflow.ai/ 

**Plan**

https://docs.rapidapi.com/docs/ive-added-my-api-to-rapidapi-now-what

Landing Page contents

I)

Who we are
Our products
II)
- RapidAPI embedding link
- Product Hunt Embedding link
- QA docs 2 3 Articles with link AnswerMe
- Quick AnswerMe tutorial ( Join Rapid API and quick tutorial. Tut is on a landing page or a medium post)
Post on (Reddit Groups, Twitter communities and

III)
Call to action

Try API on RapidAPI ( the embed link)

Join Discord

Follow the Twitter link

Subscribe to Medium
https://betaflowai.medium.com/subscribe

Follow on Reddit

IV) Sample RapidAPIs with good landing pages
https://rapidapi.com/dezgo/api/dezgo/ 
https://rapidapi.com/mediarayekme/api/zerogpt/ 
https://rapidapi.com/oopspam/api/oopspam-spam-filter/details 

V ) Sample AI services and solution providers' startup pages
https://www.blinx.ai/
https://www.simplifai.ai/ 
https://www.tensorway.com/
https://teragonia.com/ 
https://www.webtunix.com/

**Comment by betaflowai** [comment]
Resources
https://docs.github.com/en/pages/setting-up-a-github-pages-site-with-jekyll
